# Generated by Django 2.0.1 on 2018-03-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_corpcontact_corp_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEDESession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=10, verbose_name='saison')),
            ],
            options={'verbose_name': 'Session d’examen EDE'},
        ),
        migrations.AddField(
            model_name='student',
            name='date_exam',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_internal_expert', to='stages.Teacher', verbose_name='Expert interne'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='student',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_referent', to='stages.Teacher', verbose_name='Référent avant-projet'),
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.CharField(blank=True, max_length=15, verbose_name='Salle'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.TextField(blank=True, verbose_name='TD: titre provisoire'),
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.TextField(blank=True, verbose_name='TD: Titre définitif'),
        ),
        migrations.AddField(
            model_name='student',
            name='training_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_training_referent', to='stages.Teacher', verbose_name='Référent de PP'),
        ),
        migrations.AlterField(
            model_name='period',
            name='section',
            field=models.ForeignKey(limit_choices_to={'name__startswith': 'MP'}, on_delete=django.db.models.deletion.PROTECT, to='stages.Section', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_expert', to='stages.CorpContact', verbose_name='Expert externe'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.ExamEDESession'),
        ),
    ]
