# Generated by Django 2.2 on 2019-10-07 14:09

from django.db import migrations, models
from stages.models import IMPUTATION_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0022_student_entretienprof_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mark_ep',
        ),
        migrations.AddField(
            model_name='student',
            name='mark_ep',
            field=models.CharField(blank=True, choices=[('non', 'Non acquis'), ('part', 'Partiellement acquis'), ('acq', 'Acquis')], default='', max_length=5, verbose_name='Note EP'),
        ),
        migrations.AlterField(
            model_name='course',
            name='imputation',
            field=models.CharField(choices=IMPUTATION_CHOICES, max_length=12, verbose_name='Imputation'),
        ),
    ]
