# Generated by Django 2.2.6 on 2019-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0023_mark_ep_to_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark_acq',
            field=models.CharField(blank=True, choices=[('non', 'Non acquis'), ('part', 'Partiellement acquis'), ('acq', 'Acquis')], max_length=5, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='student',
            name='mark_ep_acq',
            field=models.CharField(blank=True, choices=[('non', 'Non acquis'), ('part', 'Partiellement acquis'), ('acq', 'Acquis')], max_length=5, verbose_name='Note EP'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='mark_ep',
        ),
        migrations.AddField(
            model_name='student',
            name='mark_ep',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Note EP'),
        ),
    ]
