# Generated by Django 2.0.1 on 2018-02-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0005_rename_candidat_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='residence_permits',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pas nécessaire'), (1, 'Nécessaire - OK'), (2, 'Manquante')], default=0, null=True, verbose_name='Autor. de séjour (pour les pers. étrang.)'),
        ),
    ]
